// weather_react/src/App.js
import React, { useEffect, useState } from 'react';
import axios from "axios";
import ErrorNotice from './components/UI/ErrorNotice/ErrorNotice';
import Popup from './components/UI/Popup/Popup';
import Loader from './components/UI/Loader/Loader';

function App() {
  const HIDE_ERR_TIME = 5000
  const [tempMin, setTempMin] = useState('')
  const [tempMax, setTempMax] = useState('уточняется')
  const [cities, setCities] = useState([])
  const [city, setCity] = useState({ city: undefined, country: undefined, countryCode: undefined })
  const [isCitiesLoading, setIsCitiesLoading] = useState(false)
  const [isError, setIsError] = useState(false)
  const [errorTimeout, setErrorTimeout] = useState()
  const [isCityPopup, setIsCityPopup] = useState(false)
  const [lastAjaxCountry, setLastAjaxCountry] = useState('')

  const saveCityToStorage = function () {
    Object.keys(city).forEach(key => {
      if (city[key]) {
        localStorage.setItem(key, city[key])
      }
    })
  }

  const setStartedPlace = async function () {
    let startedCity = {}
    Object.keys(city).forEach(key => {
      startedCity[key] = localStorage.getItem(key)
    })

    if (!startedCity.city || !startedCity.country || !startedCity.countryCode) {
      startedCity = await getPlaceByIp()
    }
    setCity(startedCity)
  }

  const getPlaceByIp = async function () {
    try {
      const response = await axios.get('http://ip-api.com/json/')
      return { city: response.data.city, country: response.data.country, countryCode: response.data.countryCode }
    } catch (e) {
      showError()
    }
  }

  const getCitiesByCountry = async function () {
    if (lastAjaxCountry === city.country) {
      return
    }
    setIsCitiesLoading(true)
    try {
      const response = await axios.post('https://countriesnow.space/api/v0.1/countries/cities', { country: city.country })
      setCities(response.data.data)
      setLastAjaxCountry(city.country)
    } catch (error) {
      showError(error)
    } finally {
      setIsCitiesLoading(false)
    }
  }

  const getWeather = async function () {
    if (city.city === undefined || city.country === undefined) {
      return null
    }
    try {
      const response = await axios.get("https://api.openweathermap.org/data/2.5/weather", {
        params: {
          q: `${city.city},${city.country}`,
          appid: "f07469a72d6c0229d76ce7b76a2ed11e",
          units: "metric",
          lang: 'ru',
        }
      });
      setTempMax(response.data.main.temp_max);
      setTempMin(response.data.main.temp_min);
    } catch (error) {
      showError()
    }
  }

  const showError = function () {
    if (errorTimeout) {
      window.clearTimeout(errorTimeout)
    }
    setErrorTimeout(window.setTimeout(() => { setIsError(false) }, HIDE_ERR_TIME))
    setIsError(true)
  }

  const showCityPopup = function () {
    setIsCityPopup(true)
    getCitiesByCountry()
  }

  const selectNewCity = function (evt) {
    if (cities.includes(evt.target.value)) {
      setCity({ city: evt.target.value, country: city.country, countryCode: city.countryCode })
      setIsCityPopup(false)
    }
  }

  useEffect(() => {
    saveCityToStorage()
    getWeather()
  }, [city.country, city.countryCode, city.city])

  useEffect(() => {
    setStartedPlace()
  }, [])

  return (
    <div className="App">
      <div>Ваш город "{city.city}, {city.country}"</div>
      <div>Температура сегодня: {tempMin} - {tempMax} °C</div>
      <button onClick={showCityPopup}>Выбрать другой город {city.country}</button>
      {isError === true &&
        <ErrorNotice>
          Что-то пошло не так, попробуйте повторить позже.
        </ErrorNotice>
      }
      {isCityPopup === true &&
        <Popup hide={() => setIsCityPopup(false)}>
          <input type="text" placeholder="Укажите ваш город" list="countryCities" onChange={selectNewCity} />
          <datalist id="countryCities">
            {cities.map(city =>
              <option key={city} value={city} />
            )}
          </datalist>
          {isCitiesLoading && <Loader />}
        </Popup>
      }
    </div>
  );
}

export default App;

// weather_vue/src/App.vue
<!-- TODO LIST
1. Add countries
2. Check the population of cities to show small amount of cities buttons
3. Divide into more components
 -->
<template>
  <Popup v-model:show="isPopupVisible">
    <h1>Выберете город</h1>
    <MyLoader v-model:show="isCitiesLoading" />
    <div v-if="cities.length > 0">
      <input type="text" placeholder="Укажите ваш город" list="cities" @change="setCity" />
      <datalist id="cities">
        <option v-for="(city, index) in cities" :key="index">{{ city }}</option>
      </datalist>
    </div>
  </Popup>
  <ErrorNotice v-model:show="isError"></ErrorNotice>
  <div>Ваш город "{{ city.name }}, {{ city.country }}"</div>
  <div>Температура сегодня: {{ this.tempMin }} - {{ this.tempMax }} °C</div>
  <button @click="showCityPopup">Выбрать другой город {{ city.country }}</button>
</template>

<script>
import axios from 'axios';
import Popup from './components/UI/Popup.vue';
import ErrorNotice from './components/UI/ErrorNotice.vue';
import MyLoader from './components/UI/MyLoader.vue';

export default {
  data() {
    return {
      tempMin: '',
      tempMax: 'уточняется',
      isPopupVisible: false,
      cities: [],
      countries: [],
      city: {
        name: 'Moscow',
        country: 'Russia',
        countryCode: 'RU',
      },
      country: {
        name: 'Russia',
        code: 'RU'
      },
      isCitiesLoading: true,
      isError: false,
    };
  },
  watch: {
    city(newVal) {
      this.getWeather()
      this.saveCityToLocalStorage(newVal)
    }
  },
  methods: {
    saveCityToLocalStorage(city) {
      Object.keys(city).forEach(key => {
        if (city[key]) {
          localStorage.setItem(key, city[key])
        }
      })
    },
    showError() {
      this.isError = true
      window.setTimeout(() => { this.isError = false }, 5000)
    },
    async getStartedPlace() {
      let city = {
        name: localStorage.getItem('city'),
        country: localStorage.getItem('country'),
        countryCode: localStorage.getItem('countryCode'),
      }

      if (!city.name || !city.country || !city.countryCode) {
        city = await this.getCityByIp()
      }

      this.city = city
    },
    async getCityByIp() {
      try {
        const response = await axios.get('http://ip-api.com/json/')
        return { name: response.data.city, country: response.data.country, countryCode: response.data.countryCode }
      } catch (e) {
        this.showError()
      }
    },
    setCity(evt) {
      this.city = { name: evt.target.value, country: this.city.country, countryCode: this.city.countryCode }
    },
    showCityPopup() {
      this.isPopupVisible = true
      this.getCitiesByCountry()
    },
    async getCitiesByCountry() {
      try {
        const response = await axios.post('https://countriesnow.space/api/v0.1/countries/cities', { country: this.city.country })
        this.cities = response.data.data
        this.isCitiesLoading = false
      } catch (error) {
        this.showError()
      }

    },
    async getWeather() {
      try {
        const response = await axios.get('https://api.openweathermap.org/data/2.5/weather', {
          params: {
            q: `${this.city.name},${this.city.country}`,
            appid: 'f07469a72d6c0229d76ce7b76a2ed11e',
            units: 'metric',
            lang: 'ru',
          }
        });
        this.tempMax = response.data.main.temp_max;
        this.tempMin = response.data.main.temp_min;
      } catch (error) {
        this.showError()
      }
    }
  },
  async mounted() {
    await this.getStartedPlace()
    await this.getWeather()
  },
  components: { Popup, MyLoader, ErrorNotice }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
